runtime: nodejs16
service: authorization-service
instance_class: F1
automatic_scaling:
  min_instances: 1
  max_instances: 2

service_account: datastore-user@renwick-wedding-app.iam.gserviceaccount.com
